# site settings
title: drigogetem
subtitle: by HTML5 UP
email: Aciditysux@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Wesley chapel
city: Wesley Chapel
state: FL
zip_code: 33545
country: United States of America
phone: (732)-433-1610

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/Adrianlizardo/forty-jekyll-theme/master/_config.yml
  GitLab:
  
  Instagram: drigogetem
  
  Twitter: https://twitter.com/
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
